After documentation
eclipse-tractusx/SSI-agent-lib pull request #11
Opened 2023-08-07 08:48 UTC by DominikPinsel

---
name: Pull Request Template
about: 'template for PRs that ensures basic information is provided'
title: '(feat|fix|chore|doc): _description of introduced change_'
---

## Description

Thanks for opening this contribution!
_What does this PR introduce? Does it fix a bug? Does it add a new feature? Is it enhancing documentation?_

Fixes # (issuenumber from PR destination repo)

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up to date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] Copyright and license header are present on all affected files

### Additional information

- To request a review, check out [who's involved](https://projects.eclipse.org/projects/automotive.tractusx/who) to see a list of contributors and committers
- Use the [mailing list](https://accounts.eclipse.org/mailing-list/tractusx-dev) if you are unsure, who to contact, or if want to engage in a general discussion
- Check out our guide on [how to contribute](https://eclipse-tractusx.github.io/docs/oss/how-to-contribute)
- Check out our [Release Guidelines](https://eclipse-tractusx.github.io/docs/release)
- Check out the [Eclipse Foundation contribution guidelines](https://www.eclipse.org/projects/handbook/#contributing)

2023-08-09 11:59 UTC, DominikPinsel commented
@SebastianBezold Again pretty big, but mostly documentation. I hope we can merge it :)

2023-10-10 08:27 UTC, carslen commented
Please resolve merge conflicts.

2023-10-13 05:04 UTC, florianrusch-zf requested changes
I would recommend running a Markdown linter over the changes!
The EDC already has a Github workflow for this, which could also be included in this repo: https://github.com/eclipse-tractusx/tractusx-edc/blob/5a7ff105a080fa83199dad87c8b7fe5a062cc632/.github/workflows/verify.yaml#L79-L89

If I'm correct, the linter and the respective config should be already aligned with our github page repo: https://github.com/eclipse-tractusx/eclipse-tractusx.github.io

2023-10-13 05:04 UTC, florianrusch-zf commented on docs/Feature-Create-Did.md
> +
```suggestion

```

2023-11-10 09:47 UTC, closed without merging