doc: basic java doc and java doc maven plugin added
eclipse-tractusx/SSI-agent-lib pull request #16
Opened 2023-10-12 12:02 UTC by nitin-vavdiya

## Description
Basic Java doc added with Java doc maven plugin

It will create a javadoc.jar file with `mvn install` command

To verify Java doc run `./mvnw javadoc:javadoc`

Java dock verification was added with compile goal, which means if there is any issue in Java doc then the code will no compile.

2023-10-13 06:28 UTC, borisrizov-zf commented
Hi @nitin-vavdiya, can you update the contents of the docs to some of the key components? I think we can fix the rest as we go.

2023-10-16 07:34 UTC, borisrizov-zf commented
Closes #19

2023-10-16 12:43 UTC, borisrizov-zf requested changes

2023-10-17 07:02 UTC, nitin-vavdiya commented on src/main/java/org/eclipse/tractusx/ssi/examples/ResolveDIDDoc.java
> +   * Resovle document did document.
fixed in new commit

2023-10-17 07:02 UTC, nitin-vavdiya commented on src/main/java/org/eclipse/tractusx/ssi/examples/VC.java
> +   * Create vc without proof verifiable credential.
fixed in new commit

2023-10-17 07:02 UTC, nitin-vavdiya commented
suggestions are fixed in new commit

2023-10-17 09:12 UTC, florianrusch-zf requested changes
I have not yet completed the review.

2023-10-17 09:12 UTC, florianrusch-zf commented on src/main/java/org/eclipse/tractusx/ssi/lib/SsiLibrary.java
> +/** The type Ssi library. */
```suggestion
/** The type SSI library. */
```

2023-10-17 09:13 UTC, nitin-vavdiya commented
> I have not yet completed the review.

Okay, let me know. Will fix all  suggestions in one go

2023-10-17 10:39 UTC, borisrizov-zf commented
@carslen do we need an IP check? The handbook defines "project content" as any kind of content. Although this is just class documentation, it probably still falls under the >1000 SLOC rule.

2023-10-17 11:33 UTC, carslen commented
> @carslen do we need an IP check? The handbook defines "project content" as any kind of content. Although this is just class documentation, it probably still falls under the >1000 SLOC rule.

I did not check the hole PR, but if it is only comments, then I'd approve the PR without starting a IP-Check.

2023-10-17 11:57 UTC, borisrizov-zf commented
> > @carslen do we need an IP check? The handbook defines "project content" as any kind of content. Although this is just class documentation, it probably still falls under the >1000 SLOC rule.
> 
> I did not check the hole PR, but if it is only comments, then I'd approve the PR without starting a IP-Check.

Yes, it's only Javadoc on each class. Thanks for the help :)

2023-10-24 12:06 UTC, borisrizov-zf commented
@nitin-vavdiya please rebase as we've merged two branches.

2023-10-25 06:33 UTC, nitin-vavdiya commented
> @nitin-vavdiya please rebase as we've merged two branches.

done

2023-10-25 06:36 UTC, florianrusch-zf commented
@nitin-vavdiya please change the target branch to the develop branch

2023-10-25 06:38 UTC, nitin-vavdiya commented
> @nitin-vavdiya please change the target branch to the develop branch

there is no develop branch

2023-10-25 07:10 UTC, borisrizov-zf commented
> @nitin-vavdiya please change the target branch to the develop branch

yes this repo directly merges into main.

2023-10-25 07:13 UTC, florianrusch-zf commented
> > @nitin-vavdiya please change the target branch to the develop branch
> 
> there is no develop branch

ahhh sorry, mixed the repository. :-/

2023-10-25 07:24 UTC, florianrusch-zf commented
But why is then this PR adding the following files? They should be already on the main branch.

![image](https://github.com/eclipse-tractusx/SSI-agent-lib/assets/97295414/3a686f2e-b912-4880-a715-27973da55d55)

2023-10-25 07:45 UTC, borisrizov-zf commented
@nitin-vavdiya seems your rebase didn't work correctly. can you double check?

2023-10-25 13:18 UTC, borisrizov-zf requested changes
Please recheck old comments from Florian, as the rebase has removed some changes.

2023-10-25 13:18 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/ssi/examples/VP.java
> + * his is an example class to demonstrate how to create a Verifiable Presentation in JSON-LD and KWT
```suggestion
 * This is an example class to demonstrate how to create a Verifiable Presentation in JSON-LD and KWT
```

2023-10-25 13:18 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/ssi/examples/ResolveDIDDoc.java
> +/** This is example class to demonstrate did document resolve from given did web url */
```suggestion
/** This is an example class to demonstrate did document resolve from given did web url */
```

2023-10-25 13:18 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/ssi/lib/crypt/IKeyGenerator.java
> +/** The interface Key generator. */
```suggestion
/** The interface KeyGenerator. */
```

2023-10-25 13:18 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/ssi/lib/crypt/jwk/JsonWebKey.java
> +/** The type Json web key. */
```suggestion
/** The type JsonWebKey. */
```

2023-10-25 13:18 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/ssi/lib/model/base/Base64.java
> +   * @param encoded the encoded
This is unresolved due to rebase.

2023-10-26 04:35 UTC, nitin-vavdiya commented
> Please recheck old comments from Florian, as the rebase has removed some changes.

done

2023-10-26 07:42 UTC, carslen commented
@florianrusch-zf please review if your requested changes have been applied.

2023-10-27 06:59 UTC, borisrizov-zf commented
@florianrusch-zf ping

2023-10-27 10:48 UTC, florianrusch-zf requested changes
It's way to much to do a proper review on this...I would say, lets merge it and improve the comments, when revisiting the places in later changes. WDYT? :-/

2023-10-27 10:48 UTC, florianrusch-zf commented on src/main/java/org/eclipse/tractusx/ssi/lib/crypt/x21559/x21559PublicKey.java
> +   * Instantiates a new X 21559 public key.
```suggestion
   * Instantiates a new X21559 public key.
```

2023-10-27 10:48 UTC, florianrusch-zf commented on src/main/java/org/eclipse/tractusx/ssi/lib/did/resolver/DidDocumentResolverRegistry.java
> +   * Register.
```suggestion
   * Register a new did document resolver
```

2023-10-27 10:48 UTC, florianrusch-zf commented on src/main/java/org/eclipse/tractusx/ssi/lib/did/resolver/DidDocumentResolverRegistry.java
> +   * Unregister.
```suggestion
   * Unregister a did document resolver
```

2023-10-27 11:19 UTC, nitin-vavdiya commented on src/main/java/org/eclipse/tractusx/ssi/lib/crypt/jwk/JsonWebKey.java
>    }
Please check: https://openid.net/specs/draft-jones-json-web-key-03.html

refer:  4.2.1.  JWK Key Object Members for Elliptic Curve Keys

2023-10-27 14:31 UTC, borisrizov-zf commented
This can be merged now, with the understanding that we'll improve as we go.

2023-10-30 06:05 UTC, florianrusch-zf commented
@nitin-vavdiya please apply the requested changes from @borisrizov-zf

If they got applied, we can continue with the merge.

2023-10-30 06:22 UTC, nitin-vavdiya commented
> @nitin-vavdiya please apply the requested changes from @borisrizov-zf
> 
> If they got applied, we can continue with the merge.

Yes, changes are applied

2023-10-30 07:31 UTC, florianrusch-zf commented
No, the changes are not applied:
- https://github.com/eclipse-tractusx/SSI-agent-lib/pull/16/files/26951b5a0fe67660f5e988c2f0243e6c6e5a9eea#r1371742216
- https://github.com/eclipse-tractusx/SSI-agent-lib/pull/16/files/26951b5a0fe67660f5e988c2f0243e6c6e5a9eea#r1371742617
- https://github.com/eclipse-tractusx/SSI-agent-lib/pull/16/files/26951b5a0fe67660f5e988c2f0243e6c6e5a9eea#r1371744141
- https://github.com/eclipse-tractusx/SSI-agent-lib/pull/16/files/26951b5a0fe67660f5e988c2f0243e6c6e5a9eea#r1371744665

2023-10-30 08:52 UTC, nitin-vavdiya commented
> No, the changes are not applied:
> 
> * https://github.com/eclipse-tractusx/SSI-agent-lib/pull/16/files/26951b5a0fe67660f5e988c2f0243e6c6e5a9eea#r1371742216
> * https://github.com/eclipse-tractusx/SSI-agent-lib/pull/16/files/26951b5a0fe67660f5e988c2f0243e6c6e5a9eea#r1371742617
> * https://github.com/eclipse-tractusx/SSI-agent-lib/pull/16/files/26951b5a0fe67660f5e988c2f0243e6c6e5a9eea#r1371744141
> * https://github.com/eclipse-tractusx/SSI-agent-lib/pull/16/files/26951b5a0fe67660f5e988c2f0243e6c6e5a9eea#r1371744665

done

2023-10-30 17:38 UTC, florianrusch-zf commented
build pipeline is running into a timeout while trying to pull a dependency. Will retry tomorrow

2023-10-31 07:22 UTC, borisrizov-zf commented
I think the Fraunhofer server is down.

2023-11-09 08:17 UTC, florianrusch-zf approved these changes

2023-11-09 08:18 UTC, merged