Docs add INSTALL.md
eclipse-tractusx/SSI-agent-lib pull request #25
Opened 2023-10-17 09:42 UTC by borisrizov-zf

## Description

Although TRG 1.02 doesn't require the INSTALL.md unless the project has a lengthy installation, TRG 2.03 suggests that the file is present.
Closes #24 

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ x ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ x ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2023-10-17 11:41 UTC, florianrusch-zf commented
:D Should we really add an empty file? Maybe we can add at least one sentence, or some entrypoint links (e.g. to the helm chart)

2023-10-17 11:43 UTC, borisrizov-zf commented
> :D Should we really add an empty file? Maybe we can add at least one sentence, or some entrypoint links (e.g. to the helm chart)

I'm torn myself actually... 

No Helm yet, as this is not meant to be deployed anywhere, it's just a lib.

2023-10-23 07:02 UTC, florianrusch-zf requested changes

2023-10-23 08:00 UTC, borisrizov-zf commented on README.md
>  4. After a successful build, you can include the generated JAR file in your project's dependencies.
It's included a few lines up, right before the `Build from Source` instruction.

2023-10-24 11:18 UTC, borisrizov-zf commented
@florianrusch-zf ping

2023-10-24 11:19 UTC, borisrizov-zf commented on INSTALL.md
> +
done

2023-10-24 11:37 UTC, florianrusch-zf approved these changes

2023-10-24 11:37 UTC, merged