Adding Proof Configuration to Signature
eclipse-tractusx/SSI-agent-lib pull request #77
Opened 2023-12-06 11:22 UTC by koptan

## Description

PR to include the proof configuration in the final hash during the process of creating and verifying the proof.

Therefore, the verification process should fail if any values in the Proof Configuration attributes change.

This PR should fix #34, also it's merge  #38 

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2023-12-07 11:46 UTC, koptan commented
@DominikPinsel @matgnt  @borisrizov-zf @bjoern-arnold, please for your review.

2023-12-11 15:39 UTC, matgnt commented
I would leave this to the others to review. I'm not a Java developer and don't know the libraries internal structure.

2023-12-15 08:35 UTC, DominikPinsel approved these changes
I like the idea with the new ProofSignature objects :)

2024-02-23 08:36 UTC, borisrizov-zf commented
@koptan you should rebase, because of #44

2024-03-06 09:13 UTC, koptan commented
@borisrizov-zf  Rebase is done, you can merge it 👍

2024-03-06 12:42 UTC, borisrizov-zf requested changes
Please re-check your PR, the copyright year seems to be wrong on multiple files. Also method documentation has been removed, but it is essential to have documentation to be Maven Central compliant.
I'll re-do the review after these issues have been fixed.

2024-03-06 12:42 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/ssi/examples/Verification.java
> +  public static boolean verifyED21559LD(VerifiableCredential verifiableCredential)
```suggestion
  public static boolean verifyED25519LD(VerifiableCredential verifiableCredential)
```

2024-03-06 12:42 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/ssi/lib/exception/did/DidParseException.java
> + * Copyright (c) 2021,2023 Contributors to the Eclipse Foundation
Year should be 2024

2024-03-06 12:42 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/ssi/lib/exception/json/TransformJsonLdException.java
> + * Copyright (c) 2021,2023 Contributors to the Eclipse Foundation
Year should be 2024

2024-03-06 12:42 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/ssi/lib/exception/key/InvalidPrivateKeyFormatException.java
> + * Copyright (c) 2021,2023 Contributors to the Eclipse Foundation
Year should be 2024

2024-03-07 13:17 UTC, borisrizov-zf commented
@koptan Hi, still many more files have the docs deleted, and the copyright year is not 2024. I haven't marked them explicitly, due to the sheer quantity of files. Please review them and fix these issues, before I can continue.

2024-03-13 10:42 UTC, borisrizov-zf requested changes

2024-03-13 10:42 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/ssi/lib/exception/resolver/DidWebException.java
> +
Missing `serialVersionUID = 1L`

2024-03-13 10:42 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/ssi/lib/model/did/DidParser.java
> -  /**
Restore comments for Maven Central compatibility.

2024-03-13 10:42 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/ssi/lib/proof/transform/LinkedDataTransformer.java
> + * Copyright (c) 2021,2023 Contributors to the Eclipse Foundation
Copyright year is wrong.

2024-03-13 10:42 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/ssi/lib/proof/types/jws/JWSProofVerifier.java
Missing copyright header update.

2024-03-13 10:42 UTC, borisrizov-zf commented on src/test/java/org/eclipse/tractusx/ssi/lib/proof/LinkedDataProofValidationComponentTest.java
Missing copyright header update

2024-03-13 10:42 UTC, borisrizov-zf commented on src/test/java/org/eclipse/tractusx/ssi/lib/util/identity/TestIdentityFactory.java
> -  /**
Restore comment.

2024-03-20 16:00 UTC, borisrizov-zf commented
@koptan can you point me in the right direction about the following:

verification method can be either a multibase string or a map, but I cannot see where transformation is taking place. The interface which binds these seems to be missing the option to easily extend to something like `publicKeyJWK` with an EC cipher. Am I missing something?

2024-04-03 07:30 UTC, koptan commented
@borisrizov-zf transformation is happening in TransformedLinkedData, we accept any JsonLD object as parameter.

2024-04-08 06:24 UTC, borisrizov-zf requested changes

2024-04-08 06:24 UTC, borisrizov-zf commented on src/main/java/org/eclipse/tractusx/ssi/lib/jwt/SignedJwtFactory.java
> +      var header = jwsHeaderBuilder.build();
```suggestion
      JWSHeader header = new JWSHeader.Builder(algorithm)
              .type(type)
              .keyID(issuer)
              .base64URLEncodePayload(true)
              .build();
```

2024-04-08 08:08 UTC, borisrizov-zf approved these changes

2024-04-09 07:07 UTC, borisrizov-zf commented
@koptan Hi, the branch needs rebasing, you're out of sync with main.

2024-04-10 10:50 UTC, merged